---
#------------------------------------------------------------------------------
# Playbook to CREATE Azure demo environment. 
#------------------------------------------------------------------------------

- name: PROVISION VNET SUBNETS & F5 INSTANCES
  hosts: localhost
  connection: local
  gather_facts: no
  

  environment:
    AZURE_SUBSCRIPTION_ID: "{{ az_subs_id }}"
    AZURE_CLIENT_ID: "{{ az_client_id }}"
    AZURE_SECRET: "{{ az_secret }}"
    AZURE_TENANT: "{{ az_tenant }}"

#------------------------------------------------------------------------------
# Load Variables from files 
#------------------------------------------------------------------------------

  # You need to create a file named azure_creds.yaml (update path below) with the following variables:
  #
  # az_subs_id: "--your-id-here--"

  # az_client_id: "--your-id-here--"
  # az_secret: "--your-secret-here--"
  # az_tenant: "--your-tenant-here--"

  # f5_admin_user: "--your-user-here--"
  # f5_admin_pass: "--your-password-here--"

  vars_files:
    - ../../creds/azure_creds.yaml
    - ./vars.yaml
     

#------------------------------------------------------------------------------
# Start Tasks
#------------------------------------------------------------------------------

  tasks:


  - name: CREATE RESOURCE GROUP
    azure_rm_resourcegroup:
      name: "{{ rg_name }}"
      location: "{{ az_region }}"
      tags:
        automated: "{{ automation_tool }}"
        stack: "{{ stack_name }}"
        UK-SE: "{{ uk_se_name }}"


  - name: CREATE VNET
    azure_rm_virtualnetwork:
      name: "{{ vnet_name }}"
      resource_group: "{{ rg_name }}"
      address_prefixes_cidr:
          - "{{ vnet_cidr }}"
      tags:
        automated: "{{ automation_tool }}"
        stack: "{{ stack_name }}"
        UK-SE: "{{ uk_se_name }}"


  - name: CREATE SUBNET
    azure_rm_subnet:
      name: "{{ item.name }}"
      virtual_network_name: "{{ vnet_name }}"
      resource_group: "{{ rg_name }}"
      address_prefix_cidr: "{{ item.cidr }}"
#      tags:
#        automated: "{{ automation_tool }}"
#        stack: "{{ stack_name }}"
#        UK-SE: "{{ uk_se_name }}"
    with_items: "{{ vnet_subnets }}"
    register: create_vnet_subnets


  - name: LAUNCH ARM TEMPLATE INTO AZURE  
    azure_rm_deployment:
      state: present
      resource_group_name: "{{ rg_name }}"
      template_link: "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-linux/azuredeploy.json"
      location: "{{ az_region }}"
      client_id: "{{ az_client_id }}"
      tenant: "{{ az_tenant }}"
      secret: "{{ az_secret }}"
      parameters:
        adminUsername:
          value: "{{ f5_admin_user }}"
        authenticationType:
          value: sshPublicKey
        adminPasswordOrKey:
          value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDEHcfEcI9hbkVCJjqZXBT3yG7mOJQb6Mw/QCO60aKA7nYX8C3FKNHzmY45o9oEn1EfytuD+WuFc9PSCMX5yvBrXIaGlajYQEohqOiEfjtdTZ1W8e2tWI6WcRLaAT5PXmDhk4N6jx6VcPA3s1ywej/IiH7GsOAVxf9qiUgG7PMz5xsqHQWiWCJHxOc5XXbP9Yrvb5W505bCEpeMbaGyn7sdNaYBOCBAcyAM6wAyBQpUBnVQpEpVIMJ7TrZz1Y1GF1eLw7LMEP8n9o7EpSDD8tXezwP9c8WC5wYAuUlo9NcCeGZ5rTT1VkdHXMekhK5EElEk5IQCplS3lyRX9Z0OBX9"
        ubuntuOSVersion:
          value: 16.04.0-LTS
        dnsLabelPrefix:
          value: "badger2687"
        #declarationUrl:  "NOT_SPECIFIED"
    ignore_errors: True
    
#------------------------------------------------------------------------------
# TS Curl
#------------------------------------------------------------------------------

#curl -kvu $CREDS "https://$IP/mgmt/shared/iapp/package-management-tasks" -H "Origin: https://$IP" -H 'Content-Type: application/json;charset=UTF-8' --data $DATA

#------------------------------------------------------------------------------
# End
#------------------------------------------------------------------------------
...